# Generated by Django 5.2.12 on 2026-04-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0002_channel_channelmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelmessage",
            name="flag_reason",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="channelmessage",
            name="is_flagged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="channelmessage",
            name="sentiment_label",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="channelmessage",
            name="sentiment_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="sentiment_label",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="message",
            name="sentiment_score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
