# Generated by Django 5.2.12 on 2026-04-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="confidence_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
